### ISSUE TITLE
problem with a specific kind of images

### ISSUE THREAD

**Issue by ytrezq** [darrenqc/captcha-recognizer#1]
I don’t get any results for those kind of server generated files. I suppose your program feed the captcha directly to tesseract without pre‑transformation, isn’t it ?

![cantal](https://cloud.githubusercontent.com/assets/3824869/16715547/6952422c-46e3-11e6-8ec6-a24a40f4aa45.jpeg)
![](https://cloud.githubusercontent.com/assets/3824869/16745723/6d81c488-47b7-11e6-90b2-cc7c602e33a3.jpeg)
![](https://cloud.githubusercontent.com/assets/3824869/16745724/6d88035c-47b7-11e6-958f-b969e8d3f31f.jpeg)
![](https://cloud.githubusercontent.com/assets/3824869/16745726/6dd24c64-47b7-11e6-86e4-e25f47beb76f.jpeg)
![](https://cloud.githubusercontent.com/assets/3824869/16745725/6dbfaa46-47b7-11e6-83c9-5f612498c313.jpeg)
![](https://cloud.githubusercontent.com/assets/3824869/16745727/6dde54c8-47b7-11e6-873f-171e5fa39d92.jpeg)
![ackskin](https://cloud.githubusercontent.com/assets/3824869/16745722/6d7e34bc-47b7-11e6-944d-39fc4c5f3ba4.jpeg)

**Comment by darrenqc** [comment]
yep, you have to train your own data. my program is just a simple wrapper of tesseract which provides more friendly api
